### ISSUE TITLE
[BUG] Can't transfer items from compendiums to character sheet DnD5e

### ISSUE THREAD

**Issue by shecrio** [p4535992/inventory-plus#1]
Transferring an item or spell from a compendium to a Player Character sheet generates an error for "No itemCurrent founded for the item"

Transferring it from the compendium to the Item Directory or to an NPC sheet does work, and then from Item Directory to a Character Sheet works, but from an NPC to the Character Sheet does not.

lib.js:99 inventory-plus | No itemCurrent founded for the item
warn @ lib.js:99
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus @ module.js:65
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#0 @ libWrapper-wrapper.js:189
_onDrop @ foundry.js:48283
callback @ foundry.js:44539
_handleDrop @ foundry.js:44590

**Comment by p4535992** [comment]
@shecrio try out 0.5.1 and le me know it

**Comment by shecrio** [comment]
I tried a couple compendiums from different sources, the world, the system, and a shared data compendium
Spells and features from any of those compendiums generate this error, even if I move them to the Items Directory first:

**module.js:96 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
[Detected 1 package: inventory-plus]
    at ActorSheet5eCharacter.🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus (module.js:96)
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus @ module.js:96
**

Items now work though, which is nice. Moving spells and features onto an npc also still works.

After a bit more poking around sometimes it would generate this error instead, though it wasn't consistent between types or even multiple tries from the same compendium and even the same item:

lib.js:99 inventory-plus | No target li html founded
warn @ lib.js:99
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus @ module.js:91
async function (async)
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus @ module.js:63
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#0 @ libWrapper-wrapper.js:189
_onDrop @ foundry.js:48283
callback @ foundry.js:44539
_handleDrop @ foundry.js:44590

Edit: I can make spell scrolls of spells but not add them to the spellbook which is fun and weird.

**Comment by shecrio** [comment]
0.5.2 appears to have fixed it, thanks

**Comment by shecrio** [comment]
Big sad moment, transferring items from one sheet to another generates an error

inventory-plus | No itemCurrent founded for the item
warn @ lib.js:99

**Comment by shecrio** [comment]
Trying to organize the Features and Spellbook tabs now duplicates entries instead of moving them as well.

**Comment by shecrio** [comment]
I feel like I'm harassing you at this point but 0.5.3 fixed organizing Features and Spellbook but transferring items across sheets generates this:

inventory-plus | No itemCurrent founded for the item
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus @  module.js:65
async function (async)  
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus @  module.js:63
🎁call_wrapper  @ libWrapper-wrapper.js:620
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#0  @  libWrapper-wrapper.js:189
_onDrop  @  foundry.js:48283
callback  @  foundry.js:44539
_handleDrop

**Comment by shecrio** [comment]
0.5.4 appears to have fixed all the above issues. Hopefully you do not hear from me again, right?

**Comment by p4535992** [comment]
@shecrio  version 0.5.4 working fine for you ? people tell me is a broken release.

**Comment by shecrio** [comment]
I didn't notice right away because I was focused on the above issue/s but it turns out I had the same issue they are mentioning. It looks like 0.5.5 fixed it and put back items that appeared missing but were just put back in their default Categories. 
I'll roll back to 0.5.4 to test however.
I started a fresh world on my own machine with the foundry client in the most recent Foundry and DnD5e releases and only 0.5.4 installed as a module.
It generates nothing in the f12 log when trying to move items between Categories. You can still reorganize within one Category, create new Categories, and customize those Categories weights and things as expected.

It is very likely this will not help you at all, but on my standard world where I have 50 or so modules, MaterialDeck generates an error with inventory-plus 0.5.4 when anything with a custom Category is changed. This does not happen with other versions of inventory-plus.

MaterialDeck.js:277 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '3')
[Detected 1 package: MaterialDeck]
    at getPermission (MaterialDeck.js:277)
    at MaterialDeck.js:388
    at Function._call (foundry.js:294)
    at Function.callAll (foundry.js:253)
    at Game.setupGame (foundry.js:5567)
    at async Game._initializeGameView (foundry.js:6514)
    at async Game.initialize (foundry.js:5431)
getPermission @ MaterialDeck.js:277
(anonymous) @ MaterialDeck.js:388
_call @ foundry.js:294
callAll @ foundry.js:253
setupGame @ foundry.js:5567
async function (async)
setupGame @ foundry.js:5529
_initializeGameView @ foundry.js:6514
_initializeView @ foundry.js:6490
initialize @ foundry.js:5431
async function (async)
initialize @ foundry.js:5425
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁libWrapperInit @ libWrapper-api.js:793
async function (async)
🎁libWrapperInit @ libWrapper-api.js:783
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:62701
async function (async)
window.addEventListener.once @ foundry.js:62700
backend.mjs:306 Foundry VTT | Created Setting with id [VNUbSq0YSjs2Vlpm]
backend.mjs:306 Foundry VTT | Created Setting with id [1Y7ofA43lq0aIgSy]
backend.mjs:306 Foundry VTT | Created Setting with id [cbZEC2NLjfe14XFd]
foundry.js:3053 Foundry VTT | Rendering ActorSheet5eCharacter
foundry.js:4660 Foundry VTT | Retrieved and compiled template systems/dnd5e/templates/actors/character-sheet.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/app-window.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template systems/dnd5e/templates/apps/property-attribution.html
foundry.js:297 Foundry VTT | Error thrown in hooked function '' for hook 'updateActor'
_call @ foundry.js:297
callAll @ foundry.js:253
callback @ foundry.js:10313
(anonymous) @ foundry.js:10251
_handleUpdateDocuments @ foundry.js:10251
_updateDocuments @ foundry.js:10131
async function (async)
_updateDocuments @ foundry.js:10122
update @ backend.mjs:154
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:373
update @ document.mjs:456
setFlag @ document.mjs:604
saveCategorys @ inventory-plus.js:416
changeCategoryOrder @ inventory-plus.js:323
(anonymous) @ inventory-plus.js:159
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'id')
[Detected 2 packages: MaterialDeck, inventory-plus]
    at updateActor (MaterialDeck.js:401)
    at MaterialDeck.js:413
    at Function._call (foundry.js:294)
    at Function.callAll (foundry.js:253)
    at ClientDatabaseBackend.callback (foundry.js:10313)
    at foundry.js:10251
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10251)
    at ClientDatabaseBackend._updateDocuments (foundry.js:10131)
    at async Function.updateDocuments (document.mjs:373)
    at async Actor5e.update (document.mjs:456)
    at async InventoryPlus.saveCategorys (inventory-plus.js:416)
onError @ foundry.js:319
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
_call @ foundry.js:298
callAll @ foundry.js:253
callback @ foundry.js:10313
(anonymous) @ foundry.js:10251
_handleUpdateDocuments @ foundry.js:10251
_updateDocuments @ foundry.js:10131
async function (async)
_updateDocuments @ foundry.js:10122
update @ backend.mjs:154
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:373
update @ document.mjs:456
setFlag @ document.mjs:604
saveCategorys @ inventory-plus.js:416
changeCategoryOrder @ inventory-plus.js:323
(anonymous) @ inventory-plus.js:159
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by shecrio** [comment]
I'm wrong that error still pops up with 0.5.5, though nothing actually goes wrong so I don't think its related to inventory-plus. It's just the only visible error I can get that's related to inventory-plus with 0.5.4.

**Comment by shecrio** [comment]
Again though 0.5.5 appears to completely work, so I think you fixed it despite not really knowing what was wrong. On update all items went back to their desired Categories. Items, Spells, and Features can be organized as desired, transferred between sheets, from compendiums, and between PC and NPC sheets with no issue. All the category weight settings seem to work as desired, you can't overfill a category and the image accurately reflects whether weight is counted or not, and if there is inherent weight.

**Comment by p4535992** [comment]
ty for the time you spend for the tests

**Comment by LoaneShark** [comment]
so i think i'm having this problem still? on 0.5.5

When I try to drag an object from a compendium into the character sheet, it just disappears, and I get the following warning in the console:
```
warn @ lib.js:99
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus @ module.js:276
await in 🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus (async) 
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#0 @ libWrapper-wrapper.js:189
_onDrop @ foundry.js:48283
🎁call_wrapped @ libWrapper-wrapper.js:511
_lw_ActorSheet_prototype__onDrop @ PatcherActorSheet.js:26
await in _lw_ActorSheet_prototype__onDrop (async)
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁ActorSheet.prototype._onDrop#0 @ libWrapper-wrapper.js:189
callback @ foundry.js:44539
_handleDrop
```
This doesn't happen after disabling `Enable item transfer` in the module settings (or holding Alt)

Additionally, trying to drag already existing items around within an inventory and into other categories seems to work fine, but the following error appears in the console as well:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getQuantity')
[Detected 2 packages: merchantsheetnpc, plutonium]
    at bundle.js:1279:32
    at Hooks._call (foundry.js:294:14)
    at Hooks.call (foundry.js:279:33)
    at ActorSheet5eCharacter._onDrop (foundry.js:48273:27)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at ActorSheet5eCharacter._lw_ActorSheet_prototype__onDrop (PatcherActorSheet.js:26:10)
(anonymous) @ bundle.js:1279
_call @ foundry.js:294
call @ foundry.js:279
_onDrop @ foundry.js:48273
🎁call_wrapped @ libWrapper-wrapper.js:511
_lw_ActorSheet_prototype__onDrop @ PatcherActorSheet.js:26
await in _lw_ActorSheet_prototype__onDrop (async)
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁ActorSheet.prototype._onDrop#0 @ libWrapper-wrapper.js:189
callback @ foundry.js:44539
_handleDrop @ foundry.js:44590
```

Trying to drag the item from the compendium into the items browser seems to work fine, but attempting to then drag it onto a character sheet throws the following error:
```
module.js:170 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
[Detected 1 package: inventory-plus]
    at 🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus (module.js:170:82)
🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus @ module.js:170
Promise.then (async)
🎁call_wrapper @ libWrapper-wrapper.js:630
🎁ActorSheet.prototype._onDrop#0 @ libWrapper-wrapper.js:189
callback @ foundry.js:44539
_handleDrop @ foundry.js:44590
```

**Comment by p4535992** [comment]
@LoaneShark try out 0.5.6.

**Comment by LoaneShark** [comment]
Thanks for the follow-up. I'm still seeing the same behavior, but this time don't see any error messages in the console either

**Comment by p4535992** [comment]
@LoaneShark 
Question : the issue happened with the "standard character sheet" or with the "Merchant Sheet" ?

Can you pass to me the actor ? (attach the json renaming the file with ".txt" for attach to github)

**Comment by LoaneShark** [comment]
I'm not sure why it wasn't working yesterday, but I hopped in today and it actually seems to be all working okay, or at least as I expected. I tested it on 0.5.8 as well. (I was never using the Merchant Sheet, but I did have the module installed)
