### ISSUE TITLE
[BUG] Ignore Item Weight and Inherent Weight does not work

### ISSUE THREAD

**Issue by szefo09** [p4535992/inventory-plus#10]
![image](https://user-images.githubusercontent.com/37833135/175610548-555923d0-832d-4ede-89f0-c46f608a5c95.png)

Tried to make a category for Bag of Holding, 
Filled it like this, but the weight isn't being added and Ignore Item Weight seems to do nothing.
There seem to be issues with api.js from line 85 onwards.

**Comment by szefo09** [comment]
https://github.com/p4535992/inventory-plus/blob/c6041804eb33f166e746216ef824d3235d6612c5/src/module/api.ts#L117

`CONSTANTS.INVENTORY_PLUS_MODULE_NAME` in all those those lines should be `CONSTANTS.MODULE_NAME`
or changed in constants.js into `INVENTORY_PLUS_MODULE_NAME`

**Comment by szefo09** [comment]
Also, if you have an empty category (no items in the category) with the Inherent Weight does not get added.

**Comment by p4535992** [comment]
try out 0.5.11

**Comment by szefo09** [comment]
The first issue was fixed, but the second one is still there, if you have empty category with Inherent Weight, it is not applied. A fix could be changing these lines I think - Move `section` constant declaration and `Inherent weight if statement` outside of the flag `if statement`:
https://github.com/p4535992/inventory-plus/blob/9e7853b48c853e6f39bad1d5d3110606c96fa6ae/src/module/api.ts#L105-L142

**Proposed solution:**
```ts
if (invPlusActive) { 
    // Retrieve flag 'categorys' from inventory plus module 
    const inventoryPlusCategories = <any[]>actorEntity.getFlag(CONSTANTS.MODULE_NAME, InventoryPlusFlags.CATEGORYS); 
    if (inventoryPlusCategories) { 
      // "weapon", "equipment", "consumable", "tool", "backpack", "loot" 
      let actorHasCustomCategories = false; 
      for (const categoryId in inventoryPlusCategories) { 
        const section = inventoryPlusCategories[categoryId]; 
        if ( 
          // This is a error from the inventory plus developer flags stay on 'item.data' not on the 'item' 
          //@ts-ignore 
          (item.flags && 
            //@ts-ignore 
            item.flags[CONSTANTS.MODULE_NAME]?.category === categoryId) || 
          (item.data?.flags && 
            //@ts-ignore 
            item.data?.flags[CONSTANTS.MODULE_NAME]?.category === categoryId) || 
          //@ts-ignore 
          (item.data?.data?.flags && 
            //@ts-ignore 
            item.data?.data?.flags[CONSTANTS.MODULE_NAME]?.category === categoryId) 
        ) { 
          // Ignore weight 
          if (section?.ignoreWeight == true) { 
            itemWeight = 0; 
            ignoreEquipmentCheck = true; 
          } 
 
          // EXIT FOR 
          actorHasCustomCategories = true; 
          break; 
        }
        
        // Inherent weight 
        if (Number(section?.ownWeight) > 0) {
            if (!invPlusCategoriesWeightToAdd.has(categoryId)) { 
                invPlusCategoriesWeightToAdd.set(categoryId, Number(section.ownWeight)); 
            }
        }
      }
```
