### ISSUE TITLE
[BUG] v0.5.16/v0.5.17 custom category weight tracking broken when using Variant Encumbrance module

### ISSUE THREAD

**Issue by Master807** [p4535992/inventory-plus#13]
Using Inventory+ along with the Variant Encumbrance module seems to break the weight tracking of custom categories though it worked a few versions ago. I have the compatibility options for Variant Encumbrance within Inventory+ enabled. When I disable Variant Encumbrance the weight tracking of custom categories seems to work perfectly fine again.

**Comment by p4535992** [comment]
@Master807 seem to work, can you been more specific about what is wrong on the calculation ? did you set the "inerith weight" on the custom category ? Are you sure you don't have some module setting of the Varaint Encumberance module with a different behaviour from the standard calculation weight ?

**Comment by p4535992** [comment]
@Master807  Some screenshot and exported actor can be a big help for me

**Comment by Master807** [comment]
The calculation is incorrect and doesn't seem to be working properly at all. When set to not calculate weight with the feather symbol from Variant Encumbrance at the top of the sheet it shows the actors full weight as the categories current weight. 

I'm not really sure the specifics of why the calculation is not working but it seems to be something to do with Variant Encumbrance as if I disable the module or disable the integration option in Inventory+ the custom category's weight works. I also haven't changed any of the Variant Encumbrance configurations from default. It may be a module conflict on my end but I don't see any errors in my console relating to either Inventory+ or Variant Encumbrance.

![sc1](https://user-images.githubusercontent.com/1075428/177012837-6709a26e-a075-4913-8f4b-20eb10603a28.PNG)
![sc2](https://user-images.githubusercontent.com/1075428/177012839-e87fdd23-9d73-4323-a2c7-9699f59db7a0.PNG)
![sc3](https://user-images.githubusercontent.com/1075428/177012841-4e45dbef-1cb2-49bd-a17c-9c87e645bf85.PNG)

[fvtt-Actor-nordak.txt](https://github.com/p4535992/inventory-plus/files/9033511/fvtt-Actor-nordak.txt)

**Comment by p4535992** [comment]
Ok now i see it, should be fix with version 0.9.11 of variant encumbrance

**Comment by Master807** [comment]
Updated my Variant Encumbrance module and that seems to have fixed the first bug but there is now a new bug that causes the categories weight not be to calculated if "Ignore Item Weight" is selected within the options for the custom category. I can go create a new ticket for this bug on the Variant Encumbrance GitHub page if you would like me to.
![sc1](https://user-images.githubusercontent.com/1075428/177212224-1bf5472d-7632-4d15-9c42-808ba3c4615d.PNG)
![sc2](https://user-images.githubusercontent.com/1075428/177212223-d771697f-a556-4972-bf8c-16a2b630b46e.PNG)

**Comment by p4535992** [comment]
What version of inventory-plus are you using ? it's seem a old one or at least not the latest release.

**Comment by p4535992** [comment]
@Master807 try out 0.5.18

**Comment by Master807** [comment]
The 0.5.18 update seems to have fixed the second bug and it looks like it's all working correctly now on my end. Thanks for working to get this patched so quickly and for all the work you do on Inventory+ it's one of my favourite modules to use for D&D in Foundry.

**Comment by p4535992** [comment]
thanks to you for the detailed tickets
