### ISSUE TITLE
[BUG] Unable to import spells via drag and drop to characters sheet from compendium

### ISSUE THREAD

**Issue by ibasvalen** [p4535992/inventory-plus#15]
<html>
<body>
<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/inventory-plus/module/lib/lib.js:99" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">lib.js:99</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-warning-text-color);">inventory-plus | No itemData founded for the item</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | warn | @ | lib.js:99
-- | -- | -- | --
  | 🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus | @ | module.js:98
  | async function (async) |   |  
  | 🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#inventory-plus | @ | module.js:75
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:620
  | 🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype._onDropItem#0 | @ | libWrapper-wrapper.js:189
  | _onDrop | @ | foundry.js:48283
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:511
  | _lw_ActorSheet_prototype__onDrop | @ | PatcherActorSheet.js:26
  | async function (async) |   |  
  | _lw_ActorSheet_prototype__onDrop | @ | PatcherActorSheet.js:23
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:620
  | 🎁ActorSheet.prototype._onDrop#0 | @ | libWrapper-wrapper.js:189
  | callback | @ | foundry.js:44539
  | _handleDrop

</span></div>
</body>
</html>

It was working normaly before updating to newest v0.5.18

**Comment by p4535992** [comment]
solved with 0.5.20
