### ISSUE TITLE
Custom Category displays total capacity of the entire inventory

### ISSUE THREAD

**Issue by megahead11** [p4535992/inventory-plus#18]
I created a category for a container, and set it with the following settings:
![image](https://user-images.githubusercontent.com/21242682/180236243-5609cddd-d4ec-4e9f-a37e-dc9440108698.png)
However, the container shows the weight of the entire inventory:
![image](https://user-images.githubusercontent.com/21242682/180236337-8488f031-ee79-4e8f-9159-0560ee66fc8a.png)
I am using this in conjunction with Variant Encumbrance + Midi.

Settings I am using from default is for variant encumbrance is different weight multiplier and name, and I have "Do not increase weight by quantity for no ammunition item" enabled; but these don't appear to affect this.
 
-I do not have currency weight on
-Size category weight is enabled

**Comment by p4535992** [comment]
@megahead11 can you export the actor and attach to this issue ? (rename the file with "txt" for attach the json file)

**Comment by megahead11** [comment]
As of a couple days ago, this bug disappeared and I cannot reproduce it. It may have vanished in a recent change or a change of setting. If I encounter it again, I will bump this thread.
