### ISSUE TITLE
[BUG] Update broke the module.

### ISSUE THREAD

**Issue by GRIZLEDORF** [p4535992/inventory-plus#3]
**Module Version:** v0.5.4

After the update today the module just does not work at all anymore. All items were removed from custom categories and can not put any items in any custom categories.

**Comment by p4535992** [comment]
@GRIZLEDORF 
can you give me more info?
any exception on the web console?
can you export a actor with this issue ?
what version of foundryvtt are you using ?
what version of system dnd5 are you using ?
are you on a local foundryvtt world or in some remote service as "The forge" ?

**Comment by GRIZLEDORF** [comment]
I'm sorry I didn't see your response in time. The custom categories issue was fixed but now dragging items from a compendium doesn't work again.

I was using the Client
Foundry version 9, Build 269
dnd5e 1.6.1
Local FVTT world

Thanks for all your work on this mod, it's one of my favorites and should be a core feature of foundry.
[fvtt-Actor-dread-roberts.zip](https://github.com/p4535992/inventory-plus/files/8883158/fvtt-Actor-dread-roberts.zip)

**Comment by p4535992** [comment]
ty for the support and sorry about the issue
