### ISSUE TITLE
[BUG] Unable to open PC actor when Inventory+ is enabled

### ISSUE THREAD

**Issue by gabrieljtaylor** [p4535992/inventory-plus#4]
**Module Version:** v0.5.6

**Describe the bug**
With Inventory+ enabled, many (but not all) of my PC actors cannot be opened. There is no apparent difference between the PC actors; it is not clear why the error is selective. In my case, 4/5 PC actors cannot be opened and 1/5 can. The same error is generated by all actors which cannot be opened (error listed below). I've tried disabling all Inventory+ settings to no avail; the issue only goes away when the module is completely disabled. I have used Find The Culprit to confirm that the Inventory+ is the source.

Here is the error:

> TypeError: Cannot read properties of undefined (reading 'toNearest')
> [Detected 2 packages: inventory-plus, lib-wrapper]
>     at Object.calculateWeightFromActor (api.js:153:32)
>     at 🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype.getData#inventory-plus (module.js:51:35)
>     at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
>     at 🎁game.dnd5e.applications.ActorSheet5eCharacter.prototype.getData#0 (libWrapper-wrapper.js:189:20)
>     at ActorSheet5eCharacter._render (foundry.js:3062:29)
>     at ActorSheet5eCharacter._render (foundry.js:3764:17)
>     at ActorSheet5eCharacter.render (foundry.js:3021:10)
>     at ActorSheet5eCharacter.render (foundry.js:4259:18)
>     at ActorDirectory._onClickDocumentName (foundry.js:47609:16)
>     at HTMLOListElement.dispatch (jquery.min.js:2:43064)
>     at v.handle (jquery.min.js:2:41048)

**To Reproduce**
1. Have Inventory+ enabled
2. Attempt to open various PC actors
3. Many actors' sheets will not open and the aforementioned error will appear in the log

**Expected behavior**
The actor sheet opens as expected.

**Screenshots**
n/a, unless you want a screenshot of the error listed above.

**Browser:**
Microsoft Edge 102.0.1245.33

**Foundry Version:** 
9.269

**Game System:** 
D&D 5E 1.6.3

**Additional context**
I've tried disabling all other modules save Inventory+ save libWrapper (via Find The Culprit) and the error persists.

**Comment by p4535992** [comment]
@gabrieljtaylor try out 0.5.7

**Comment by gabrieljtaylor** [comment]
@p4535992 - that seems to have done the trick; I can no longer reproduce the issue and character sheets are opening as expected. Thanks for the rapid fix!
