### ISSUE TITLE
Carry Capacity Issues

### ISSUE THREAD

**Issue by Monsamoai** [p4535992/inventory-plus#7]
**Module Version:** v0.5.8

**Bug:**
The module seems to have issues with carry capacity and modifying it in different areas. Not only does it not calculate "Inherent Weight" or "Ignore Item Weight" correctly (failing to change the weight at all) but there are some instances where the carry weight on characters spike to the thousands.

**To Reproduce**
1. Create character
2. Go to inventory
3. Add custom category
4. Change "Inherent Weight" or "Ignore Item Weight."
5. Observe Carry capacity, see bug.

The spikes in carry weight seem to be random. When modifying the bag, moving items, or closing the character sheet, it sometimes spikes to the thousands.

**Expected behavior**
Changing "Inherent Weight" or "Ignore Item Weight" should affect carry capacity accordingly, and the weight should not spike randomly.

**Screenshots**

Module failure to modify carry capacity.
<img width="540" alt="Screenshot 2022-06-20 112934" src="https://user-images.githubusercontent.com/64101159/174668631-4fb271d3-4daa-442f-bda9-164fa0053f69.png">

Abnormal weight spike.
<img width="556" alt="oluikyjtrewqa" src="https://user-images.githubusercontent.com/64101159/174668669-65f88d12-a613-41b7-add9-c1cb066acefe.png">

**Foundry Version:** 9 - Build 269

**Game System:** D&D 5e (1.6.3)

**Additional context**
None, issue still arose without any other modules.

**Comment by p4535992** [comment]
Should be solved with 0.5.9

**Comment by Ikabodo** [comment]
There seems to be some minor issues left with this but only with inherent weight. I'm not sure exactly what happens but it looks like it adds the inherent weight each for every item in the category?

![image](https://user-images.githubusercontent.com/7766890/174972718-7d9b3f73-14de-420a-822c-b82188905ecc.png)
This is with inherent weight 0.

![image](https://user-images.githubusercontent.com/7766890/174972866-93cc4615-ab40-4664-813c-501d53cce875.png)
This is with inherent weight 10.

![image](https://user-images.githubusercontent.com/7766890/174973028-e5f029a5-b857-4ad9-b322-02d0561b30d7.png)
But oddly, this is with inherent weight 1.

**Comment by DOMtheDM** [comment]
I'm using 0.5.9 and experiencing the same issue. My player has a Bag of Holding with an Inherent Weight of 15 and his total weight is over 1500 even though he isn't carrying much. If I drop the Inherent Weight of the bag to 0, his weight drops to around 150. DnD5e 1.6.3 Foundry V9 Build 269

**Comment by p4535992** [comment]
try out 0.5.10
