### ISSUE TITLE
Re-enable def Cat.

### ISSUE THREAD

**Issue by LtDerek** [p4535992/inventory-plus#8]
I'm unsure what this feature does, and I would prefer to have the option to hide it to reduce clutter.

**Comment by p4535992** [comment]
Before fix this with a module settings can i ask you , what can i do for make the behaviour more clear ?
Like some better label or text on the dialog content, ecc.
The purpose of that button is to restore the system default categories (weapon, toll, etc.) in case you delete them and want to return to the initial state.

**Comment by LtDerek** [comment]
I think it's clear enough already. My confusion is more my own problem than one with the module xD. In hindsight it's very obvious.


Though being able to disable it would be nice,  I'm mainly concerned about players clicking it by accident.

**Comment by p4535992** [comment]
on version 0.5.11 by default is visible only to GM, there is a module settigns for hide the button to everyone included the gm
